#!/usr/bin/env bash
set -u

ROOT="${HOME}/lean-ai-ml-math"
PROJECT="${ROOT}/AIMLMath"
SANITY="${PROJECT}/AIMLMath/Sanity.lean"
SENTINEL="/- GENERATED BY mathematician-ai-ml init_aiml_workspace.sh; safe to overwrite. -/"

if ! command -v lean >/dev/null 2>&1; then
  echo "Missing required command: lean" >&2
  exit 1
fi

if ! command -v lake >/dev/null 2>&1; then
  echo "Missing required command: lake" >&2
  exit 1
fi

mkdir -p "$ROOT"

has_lake_config() {
  [[ -f "${PROJECT}/lakefile.lean" || -f "${PROJECT}/lakefile.toml" ]]
}

if [[ -d "$PROJECT" ]] && ! has_lake_config; then
  backup="${PROJECT}.backup.$(date +%Y%m%d-%H%M%S)"
  mv "$PROJECT" "$backup"
  echo "Moved non-Lake AIMLMath directory to ${backup}"
fi

created_mathlib=0
fallback_non_mathlib=0

if ! has_lake_config; then
  (
    cd "$ROOT" || exit 1
    lake new AIMLMath math.lean
  )
  status=$?
  if [[ $status -eq 0 ]]; then
    created_mathlib=1
  else
    rm -rf "$PROJECT"
    (
      cd "$ROOT" || exit 1
      lake new AIMLMath
    ) || exit 1
    fallback_non_mathlib=1
    echo "Mathlib project creation failed; created non-mathlib Lean project. Mathlib-dependent checks are Lean-attempted but incomplete."
  fi
fi

if [[ $fallback_non_mathlib -eq 1 ]]; then
  mkdir -p "$(dirname "$SANITY")"
  if [[ -f "$SANITY" ]] && ! head -n 1 "$SANITY" | grep -Fxq "$SENTINEL"; then
    echo "Existing Sanity.lean lacks generated sentinel; preserving user file."
  else
    cat > "$SANITY" <<EOF
$SENTINEL

/- Mathlib is unavailable in this fallback project.
   Re-run this script after Lake can create a mathlib project. -/

#check Nat
EOF
  fi
  exit 2
fi

cd "$PROJECT" || exit 1

if [[ -f lakefile.lean || -f lakefile.toml ]]; then
  lake update || exit 1
  lake exe cache get || true
fi

probe="$(mktemp -t aiml-sanity-probe).lean"
cat > "$probe" <<'EOF'
import Mathlib

#check Real
#check Matrix
#check MeasureTheory.ProbabilityMeasure
#check MeasureTheory.IsProbabilityMeasure
#check ConvexOn
EOF

probe_ok=1
if lake env lean "$probe" >/tmp/aiml-sanity-probe.out 2>/tmp/aiml-sanity-probe.err; then
  probe_ok=0
fi

mkdir -p "$(dirname "$SANITY")"
if [[ -f "$SANITY" ]] && ! head -n 1 "$SANITY" | grep -Fxq "$SENTINEL"; then
  echo "Existing Sanity.lean lacks generated sentinel; preserving user file."
else
  if [[ $probe_ok -eq 0 ]]; then
    cat > "$SANITY" <<EOF
$SENTINEL
import Mathlib

#check Real
#check Matrix
#check MeasureTheory.ProbabilityMeasure
#check MeasureTheory.IsProbabilityMeasure
#check ConvexOn
EOF
  else
    cat > "$SANITY" <<EOF
$SENTINEL
import Mathlib

#check Real
#check Matrix
-- #check MeasureTheory.ProbabilityMeasure -- unavailable in current Mathlib probe
-- #check MeasureTheory.IsProbabilityMeasure -- unavailable in current Mathlib probe
#check ConvexOn
EOF
    echo "Mathlib sanity probe reported unavailable identifiers. See /tmp/aiml-sanity-probe.err"
  fi
fi

if lake build; then
  if [[ $probe_ok -eq 0 ]]; then
    exit 0
  fi
  exit 2
fi

if [[ $created_mathlib -eq 1 || $probe_ok -ne 0 ]]; then
  echo "Mathlib-dependent workspace build failed or has dependency gaps."
  exit 2
fi

exit 1
